# config for training resnet/gnet on conventional dir structure

dataset:
  name: gnet_val
  datadir: ${base_dir}/met-gbm/gnet/val
  keep_in_memory: True
  format: png
  shuffle: False
  tag: 'val'

transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomRotation
      degrees: 15
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    # - _target_: torchvision.transforms.Normalize
    #   mean: [0.485, 0.456, 0.406]
    #   std: [0.229, 0.224, 0.225]  
