dataset:
  name: radnec_val
  imgdir: ${base_dir}/nnUNet_raw/Dataset140_RadNecClassify/imagesTr
  lbldir: ${base_dir}/nnUNet_raw/Dataset140_RadNecClassify/labelsTr
  split: "val"
  keep_in_memory: True
  format: png
  shuffle: True
transforms:
  # - _target_: pc_sam.datasets.transforms.NormalizePoints
  # - _target_: pc_sam.datasets.transforms.NormalizeColor
  #   mean: 0.5
  #   std: 0.5
  # - _target_: pc_sam.datasets.transforms.RandomSampleMask
  #   num_samples: 2
  # - _target_: pc_sam.datasets.transforms.RandomSample
  #   num_samples: ${num_samples}
  # - _target_: pc_sam.datasets.transforms.RandomScale
  #   low: 0.8
  #   high: 1.0
  # - _target_: pc_sam.datasets.transforms.RandomRotatePerbuate
  # - _target_: pc_sam.datasets.transforms.RandomRotateAlongAxis
  # - _target_: pc_sam.datasets.transforms.ToTensor