dataset:
  name: radnec_train
  imgdir: ${base_dir}/nnUNet_raw/Dataset139_RadNecClassify/imagesTr
  lbldir: ${base_dir}/nnUNet_raw/Dataset139_RadNecClassify/labelsTr
  split: "train"
  keep_in_memory: False
  format: png
  shuffle: False
transforms:
  # - _target_: pc_sam.datasets.transforms.NormalizePoints
  # - _target_: pc_sam.datasets.transforms.NormalizeColor
  #   mean: 0.5
  #   std: 0.5
  - _target_: transforms.RandomSampleMask
    num_samples: 2
  - _target_: transforms.RandomSample
    num_samples: ${num_samples}
  # - _target_: pc_sam.datasets.transforms.Crop
  #   centroid: ${}
  # - _target_: pc_sam.datasets.transforms.RandomScale
  #   low: 0.8
  #   high: 1.0
  # - _target_: pc_sam.datasets.transforms.RandomRotatePerbuate
  # - _target_: pc_sam.datasets.transforms.RandomRotateAlongAxis
  - _target_: transforms.ToTensor