dataset:
  name: radnec_train
  imgdir: ${base_dir}/nnUNet_raw/Dataset140_RadNecClassify/imagesTr
  lbldir: ${base_dir}/nnUNet_raw/Dataset140_RadNecClassify/labelsTr
  split: "train"
  keep_in_memory: True
  format: png
  shuffle: False

transforms:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.RandomRotation
      degrees: 15
    - _target_: torchvision.transforms.ColorJitter
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1