defaults:
  - dataset@train_dataset: radnec_train 
  - dataset@val_dataset: radnec_val
  - dataset@test_dataset: radnec_test
  - loss: default # 
  - paths
  - model: default # default.yaml 

hydra:
  run:
    dir: ${base_dir}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    
# Global variables
num_samples: 10000
decimate: 0

# For 4GB GPU.
train_dataloader:
  batch_size: 16
  num_workers: 2
  shuffle: False
  drop_last: True

val_freq: 5
val_dataloader:
  batch_size: 1
  num_workers: 2
  shuffle: False
  drop_last: False

lr: 3e-4
weight_decay: 0.1
max_grad_value: 1.0
gradient_accumulation_steps: 1
save_freq: 10

scheduler:
  _target_: optim.lr_scheduler.WarmupMultiStepLR
  milestones: [400, 500]
  warmup_iters: 300
  warmup_factor: 0.001
  gamma: 0.1

pretrained_ckpt_path: ""
max_epochs: 50
max_steps: 5000000

# Logging
log_with: tensorboard


